server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 8.130.103.223:8848
    gateway:
      routes:
        - id: order-server
          uri: lb://order-server
          predicates:
            - Path=/order/**
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/user/**
