server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: wupeng1221
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order-server
  cloud:
    nacos:
      server-addr: 8.130.103.223:8848
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  client:
    config:
      default:
        logger-level: none
  httpclient:
    enabled: true #支持httpclient
    max-connections: 200 #最大链接数
    max-connections-per-route: 50 #单个链接的最大连接数
